### ISSUE TITLE
Make interface changes

### ISSUE THREAD

**Issue by jlegrone** [Bernie-2016/data-team-uploader#18]
https://docs.google.com/document/d/1kaAaKLwVxlJ5cidv1qLDoe3B0yJbQ7uBBYA82wVkyc4/edit
- [x] At the top of the form below the title: “Click here for picture-taking directions”
- [x] Your Email
  - Add instruction "Use the same email address you used to login when you created your event on berniesanders.com"
- [x] I am a: (Radio buttons)
  - Bernie Sanders volunteer
  - Bernie Sanders staff member
- [x] Event Location section
  - Event City:  - open entry field
  - Event State: - two letter state abbreviation drop down
- [x] What are you uploading?  (Radio buttons)
  - One page event sheets
  - Two or more page event sheets Add instruction: Write host’s name on all pages!
  - Sign-in sheets
- [x] Remove notes field
- [x] Upload attachment:
  - Add instruction: To upload multiple files, please select all files at once before clicking “open”.

**Comment by jlegrone** [comment]
Ask @pauladorfman on #berniebuilders about how she wants to handle submissions differently from volunteers/staff

**Comment by jeffomatic** [comment]
@jlegrone Can you clarify what is left to be done here? There's a [link](https://script.google.com/macros/s/AKfycbwqIMX9iqNIWbOKo-31Z8dRl0WFHNJuR2JnUUfASDquN8OQa0Y/exec) in the Google Doc that appears to contain a full implementation of the features described in this issue, as well as the post-upload view (in the form of a modal) described in #19.

**Comment by jlegrone** [comment]
@jeffomatic I'm assigning @oranges13 to this (that's who had made the app linked to from the google doc). In the meantime please feel free to take a look at some other open issues.

**Comment by jeffomatic** [comment]
@jlegrone Sounds good. I'd like to take a look at the other issues, but I intend to hold off from doing any heavy lifting until @oranges13's PR (#20) is finalized, as there are a lot of changes.
