### ISSUE TITLE
Change where uploaded files are saved 

### ISSUE THREAD

**Issue by marynish** [Bernie-2016/data-team-uploader#25]
When a volunteer uploads:
- a single-page event type (ev-i), the file should go into the folder 'Event Sheets - Single Page',
- a multiple-page event type (ev-m), the file should go into the folder '[Event Sheets - Multiple Pages](https://drive.google.com/folderview?id=0Bw9Apc7v0NrZc1EwdVI2VU9VSzA&usp=drive_web)', and
- a sign-in sheet (si), the file should go into the folder 'Signins'.

When new files are uploaded, they should no longer automatically be added to the spreadsheet. This section of the uploadFileToDrive function needs to be removed:

```
if(form.fileType == "ev-i" || form.fileType == "si") {
  addRowToSpreadsheet(url, fileName, form.fileType, form.email);
}
```

**Comment by oranges13** [comment]
Hello! They asked to have that functionality added a few months ago. Are we now requiring manual processing again?

**Comment by marynish** [comment]
Hello! Yes - because of the errors in the upload process, there needs to be manual intervention before the event makes it on the sheet. Tara (@phoenix_tara) made a high priority request to me get that automated record addition stopped.
- Mary (@marynish)
  PS - I know what needs to change, but am not technically a 'developer.' Just a business analyst / solution architect with enough skills to be dangerous ;)

**Comment by oranges13** [comment]
Ok cool! Just wanted to confirm before doing it ☺
