### ISSUE TITLE
Log new submissions in spreadsheet

### ISSUE THREAD

**Issue by jlegrone** [Bernie-2016/data-team-uploader#5]

**Comment by jeffomatic** [comment]
@jlegrone Would it be possible to get more detail on this feature?

**Comment by oranges13** [comment]
Hey @jeffomatic , I'm unsure of the details of this as well, however I believe that what we're already doing fulfills this requirement since it posts everything to the spreadsheets anyway. Unless they truly want just a log (similar to what a google form would give you)
